### PR TITLE
Full Node Guide: OS X Instructions Minor Tweak

### PR DESCRIPTION
**Pull request by harding**
This just adds the following text to the end of your instructions:

2015-07-22-150425_619x319_scrot

Everything else in your PR looked good to me.  Thanks so much for taking the time to do this!

### CODE REVIEW

**Comment by oliverdowling** [comment]
Accepted your change.

Note that Bitcoin Core daemon is not included with the Mac version. The Bitcoin Core GitHub repository includes [instructions to build bitcoind](https://github.com/bitcoin/bitcoin/blob/master/doc/build-osx.md), or you can run Bitcoin Core with the server and RPC options in a Bitcoin.conf file.

I would assume you'd just want instructions for running it as a server and accepting RPC connections, rather than including build instructions? If so, let me know and I can try and write up some instructions and take some screenshots for that if you like.

Once it's running, you can use cURL to do the RPC commands since there is no bitcoind. I found an [answer on Bitcoin Stack Exchange by Gavin Andresen](http://bitcoin.stackexchange.com/questions/2570/bitcoin-qt-command-line-control-on-mac/2612#2612) about it.

**Comment by harding** [comment]
Thanks!

Instructions on using the daemon mode would be great, but they should be a separate pull request (PR) so that I can merge your first PR more quickly.  Are you sure the OS X package doesn't include `bitcoind` and/or `bitcoin-cli` somewhere?  [This issue](https://github.com/bitcoin/bitcoin/issues/664) linked from the StackExchange answer you provided indicates they may now be available.

**Comment by oliverdowling** [comment]
The default download, the dmg file, does not, however, I just checked the tar.gz version, and that does:

```bash
$ curl -O https://bitcoin.org/bin/bitcoin-core-0.11.0/bitcoin-0.11.0-osx64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 23.5M  100 23.5M    0     0  1175k      0  0:00:20  0:00:20 --:--:-- 1949k
$ tar xzf bitcoin-0.11.0-osx64.tar.gz 
$ ls -al bitcoin-0.11.0/bin/
total 112216
drwxr-xr-x  8 oliver  staff       272  1 Jun 10:00 .
drwxr-xr-x  5 oliver  staff       170  1 Jun 10:00 ..
-rwxr-xr-x  1 oliver  staff   1648300  1 Jun 10:00 bitcoin-cli
-rwxr-xr-x  1 oliver  staff  23634096  1 Jun 10:00 bitcoin-qt
-rwxr-xr-x  1 oliver  staff   1137036  1 Jun 10:00 bitcoin-tx
-rwxr-xr-x  1 oliver  staff   6789760  1 Jun 10:00 bitcoind
-rwxr-xr-x  1 oliver  staff   8505380  1 Jun 10:00 test_bitcoin
-rwxr-xr-x  1 oliver  staff  15727668  1 Jun 10:00 test_bitcoin-qt
```

**Comment by harding** [comment]
Ah, that makes sense.  I always wondered why there were two downloads for Mac... :-)

If using the tarball is a reasonable option, I think that would be better for access to `bitcoin-cli` as well as being able to keep the daemon instructions for Mac similar to the daemon instructions on the other OSes.  However, whatever you feel comfortable documenting works for me.

Thanks again!

**Comment by oliverdowling** [comment]
The install and run instructions are the same as for "Other Linux Distributions" with the exception of the filename and the path to Bitcoin.conf

Seems a bit silly to include all the alternate install instructions, but I'll write it up in another pull request if/when I get a chance.

**Comment by harding** [comment]
@oliverdowling then it's fine to just say that, provide the OS X filename and configuration path, and link to the Linux instructions: `[Other Linux Instructions](#other-linux-daemon)`

**Pull request merged**
